language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly-2018-02-27
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
    - travis-ci/sqlite3
    - ubuntu-toolchain-r-test
    packages:
    - sqlite3
    - gcc-5
    - g++-5
env:
  - CXX=g++-5 CC=gcc-5
cache:
  cargo: true
  apt: true
  directories:
  - $HOME/libsodium

install:
  - ./travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH

script:
  - cargo build --verbose
  - RUST_LOG=error cargo test --verbose
  - 'if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then RUST_LOG=error cargo test --verbose --features benchmarks; fi'
  - cargo doc
